### ISSUE TITLE
App crashes after "Initialized the room successfully"

### ISSUE THREAD

**Issue by abdulkarimkhaled** [senseobservationsystems/react-native-gruveo#6]
I'm using react-native-gruveo and it works well on iOS but crashes on android devices.

And here is the logcat crash:

2021-01-11 14:54:57.823 23102-23102/com.re3aya247.doctor E/AndroidRuntime: FATAL EXCEPTION: main Process: com.re3aya247.doctor, PID: 23102 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.re3aya247.doctor/com.gruveo.sdk.ui.CallActivity}: android.view.InflateException: Binary XML file line #17 in com.re3aya247.doctor:layout/abc_screen_simple: Binary XML file line #17 in com.re3aya247.doctor:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) Caused by: android.view.InflateException: Binary XML file line #17 in com.re3aya247.doctor:layout/abc_screen_simple: Binary XML file line #17 in com.re3aya247.doctor:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout Caused by: android.view.InflateException: Binary XML file line #17 in com.re3aya247.doctor:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference at uk.co.chrisjenx.calligraphy.ReflectionUtils.getValue(ReflectionUtils.java:29) at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:203) at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239) at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) at android.view.LayoutInflater.inflate(LayoutInflater.java:659) at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) at android.view.LayoutInflater.inflate(LayoutInflater.java:534) at android.view.LayoutInflater.inflate(LayoutInflater.java:481) at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:773) at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659) at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552) at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) at com.gruveo.sdk.ui.CallActivity.onCreate(CallActivity.kt:20) at android.app.Activity.performCreate(Activity.java:7802) at android.app.Activity.performCreate(Activity.java:7791) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 2021-01-11 14:54:57.823 23102-23102/com.re3aya247.doctor E/AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:7356) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 2021-01-11 14:54:57.831 23102-23102/com.re3aya247.doctor I/Process: Sending signal. PID: 23102 SIG: 9

**Comment by abdulkarimkhaled** [comment]
Solved it by adding this line: implementation 'org.bitbucket.gruveo:gruveo-sdk-android:0.7.2' to dependencies in android/app/build.gradle
